In [3]:
import numpy as np

In [4]:
def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return sigmoid(z)*(1-sigmoid(z))

In [44]:
Network = [4, 3, 2]
x = np.arange(4).reshape(4, 1)
n_layers = len(Network)

In [43]:
# self.weights, self.activation, self.bias, self.z, self.derivative, self.deltas 

In [ ]:
# 1. forrward propogate --- self.activation 

In [244]:
Network = [4, 3, 2]
n_layers = len(Network)
weights = [np.random.rand(Network[i + 1], Network[i]) for i in range(n_layers - 1)]
weights.insert(0, None)
bias = [np.random.rand(Network[i + 1], 1) for i in range(n_layers - 1)]
bias.insert(0, None)
for i in weights:
    print(i)
    print()

None

[[0.22423587 0.62930027 0.01575724 0.79398696]
 [0.42939263 0.87917983 0.64310596 0.54329565]
 [0.99130258 0.16584911 0.05937874 0.79392508]]

[[0.14959683 0.33589773 0.8729455 ]
 [0.93016295 0.55417348 0.23478442]]



TypeError: object of type 'NoneType' has no len()

In [127]:
activation = [np.array(x)]
activation # W

[array([[0],
        [1],
        [2],
        [3]])]

In [216]:
def propogate_forward(x, Network, weights, bias):
    # # Feedforward: For each l=2,3,…,L compute zl=wlal−1+bl and al=σ(zl).
    activation = [np.array(x)]
    z = [None]
    for i in range(1, n_layers):           
        z_i = np.dot(weights[i], activation[i - 1])
        z.append(z_i)
        activation_i = sigmoid(z_i) # activation function 
        activation.append(activation_i)
    return activation, z

        
activation, z = propogate_forward(x, Network, weights, bias)
activation

[array([[0],
        [1],
        [2],
        [3]]),
 array([[0.93921099],
        [0.9530413 ],
        [0.99363811]]),
 array([[0.75669154],
        [0.81724191]])]

In [217]:
# Output error δL: Compute the vector δL=∇aC⊙σ′(zL).
delta = np.copy(activation).tolist()
last = n_layers - 1
delta[last] = activation[last] * sigmoid_prime(z[last])*100 # last delta 
delta

[array([[0],
        [1],
        [2],
        [3]]),
 array([[0.93921099],
        [0.9530413 ],
        [0.99363811]]),
 array([[13.93140667],
        [12.20612678]])]

In [229]:
for layer in range(last-1, 0, -1):
    delta[layer] = np.dot(weights[layer + 1].T, delta[layer + 1]) * sigmoid_prime(z[layer])
delta

[array([[0],
        [1],
        [2],
        [3]]),
 array([[0.75647468],
        [0.52172294],
        [0.06701875]]),
 array([[13.93140667],
        [12.20612678]])]

In [242]:
weights_grad = np.copy(weights)
bias_grad = np.copy(bias)
for layer in range(last, 0, -1):
    weights_grad[layer] = np.dot(delta[layer], activation[layer-1].T)
    bias_grad[layer] = delta[layer]
weights   

[None,
 array([[0.33929472, 0.24190475, 0.8900286 , 0.23855637],
        [0.43189484, 0.22946939, 0.04327296, 0.89812485],
        [0.49140208, 0.98858734, 0.93271727, 0.73234176]]),
 array([[0.69515934, 0.27001539, 0.22582522],
        [0.29207915, 0.64688721, 0.61082357]])]

In [245]:
alpha = 0.01
for layer in range(last, 0, -1):
    weights[layer] += alpha * weights_grad[layer]
    bias[layer] += alpha * bias_grad[layer]
    

In [246]:
weights

[None,
 array([[0.22423587, 0.63686501, 0.03088673, 0.8166812 ],
        [0.42939263, 0.88439705, 0.65354041, 0.55894734],
        [0.99130258, 0.1665193 , 0.06071912, 0.79593564]]),
 array([[0.28044213, 0.46866979, 1.01137326],
        [1.04480424, 0.67050291, 0.35606914]])]

In [266]:
def init_all():
    Network = [8, 3, 2, 1]
    x = np.arange(8).reshape(8, 1)
    n_layers = len(Network)
    weights = [np.random.rand(Network[i + 1], Network[i]) for i in range(n_layers - 1)]
    weights.insert(0, None)
    bias = [np.random.rand(Network[i + 1], 1) for i in range(n_layers - 1)]
    bias.insert(0, None)
init_all()
weights

[None,
 array([[0.22423587, 0.63686501, 0.03088673, 0.8166812 ],
        [0.42939263, 0.88439705, 0.65354041, 0.55894734],
        [0.99130258, 0.1665193 , 0.06071912, 0.79593564]]),
 array([[0.28044213, 0.46866979, 1.01137326],
        [1.04480424, 0.67050291, 0.35606914]])]

In [264]:
def propogate_forward(x, Network, weights, bias):
    # # Feedforward: For each l=2,3,…,L compute zl=wlal−1+bl and al=σ(zl).
    activation = [np.array(x)]
    z = [None]
    
    for i in range(1, n_layers):           
        z_i = np.dot(weights[i], activation[i - 1])
        z.append(z_i)
        activation_i = sigmoid(z_i) # activation function 
        activation.append(activation_i)
    return activation, z
activation, z = propogate_forward(x, Network, weights, bias)

ValueError: shapes (3,4) and (8,1) not aligned: 4 (dim 1) != 8 (dim 0)

In [289]:
def propogate_back(weights, bias):
    
    # Calculate deltas 
    delta = np.copy(activation).tolist()
    last = n_layers - 1
    delta[last] = activation[last] * sigmoid_prime(z[last]) 
    for layer in range(last-1, 0, -1):
        delta[layer] = np.dot(weights[layer + 1].T, delta[layer + 1]) * sigmoid_prime(z[layer])
    
    # Calculate gradients
    weights_grad = np.copy(weights)
    bias_grad = np.copy(bias)
    
    for layer in range(last, 0, -1):
        weights_grad[layer] = np.dot(delta[layer], activation[layer-1].T)
        bias_grad[layer] = delta[layer]
    return weights_grad, bias_grad
        

In [260]:
def Gradient_descent():
    # Update weights 
        alpha = 0.01
        for layer in range(last, 0, -1):
            weights[layer] += alpha * weights_grad[layer]
            bias[layer] += alpha * bias_grad[layer]
    


In [286]:
in_features, out_features = 2, 4
x = np.arange(8).reshape(4, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [290]:
scale = 1 / np.sqrt(in_features)
W = np.random.uniform(-scale, scale, (in_features, out_features))
b = np.zeros((1, out_features))
b.T.shape, W.T.shape, x.shape

((4, 1), (4, 2), (4, 2))

In [301]:
# Получается что нейронка считается для каждого трейнинг сэмпла отдельно 
# на вход дается всегда одна пара  (x1, x2)
# но мы можем посчитать активации сразу для всех
for i in W:
    curr = np.mean(i)
    print(i)
    print(curr)

[ 0.1878253   0.44682959 -0.68614078 -0.5311421 ]
-0.14565699995811413
[ 0.53450605  0.70464654 -0.41298305  0.53513272]
0.34032556308674594


In [309]:
# a = [i for i in range(10)]
a = [0] + [i for i in range(1, 10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# Generate weights and bias:
coef_init = self._random_state.uniform(-init_bound, init_bound,
                                       (fan_in, fan_out))
intercept_init = self._random_state.uniform(-init_bound, init_bound,
                                            fan_out)

In [315]:
a = np.array([[1, 2],
              [3, 4],
              [2, 2]])
a.shape
# 2.5
np.mean(a, axis=0) # Среднее по столбцам = dim = n_samples

(3, 2)

In [316]:
np.mean(a, axis=0)

array([2.        , 2.66666667])

In [318]:
np.mean(a, axis=1) # dim = колву строк 

(3,)

In [327]:
weights = np.arange(15).reshape(3, 5) # Веса
X = np.arange(15).reshape(5, 3) # 5 наблюдений по три фичи
activation = weights @ X
activation.shape # 3 нейрона для каждого наблюдения в колонках

(3, 3)

In [331]:
grad = 0.1 * np.copy(activation)
grad, activation

(array([[ 9. , 10. , 11. ],
        [24. , 27.5, 31. ],
        [39. , 45. , 51. ]]),
 array([[ 90, 100, 110],
        [240, 275, 310],
        [390, 450, 510]]))

In [334]:
weights.shape

(3, 5)

In [346]:
# (a_L - y) * sigmoid(activation)
weights_1 = np.arange(6).reshape(2, 3)
weights_1.shape, activation.shape

((2, 3), (3, 3))

In [347]:
weights_1 @ activation # 1 layer activation

array([[1020, 1175, 1330],
       [3180, 3650, 4120]])